### PR TITLE
Implement `Enumerable(T)` to `Maybe(T)`

### PR DESCRIPTION
**Pull request by moba1**
Add `#each` method and include `Enumerable(T)`

### CODE REVIEW

**Comment by moba1** [comment]
By implementing `Enumerable(T)`, can use `cycle` method.

**Comment by moba1** [comment]
But, this module may not be necessary now.
I implemented this module to previous my package, hence I implements this package with gay abandon.

**Comment by alex-lairan** [comment]
I don't know when use it.

Enumerable look good for a List monad, but for a Maybe :/

**Comment by moba1** [comment]
Sorry.
I drop this PR.

**Comment by alex-lairan** [comment]
Don't feel sorry ;) 

You can arge how to use it with example.

You seems to know more things than me about monads.

**Comment by moba1** [comment]
I thought about this too, but most methods which are able to use by implement `Enumerable` can be implemented in other ways.
So the meaning of implementing them is rather thin.

**Comment by moba1** [comment]
If I’m forced to say, can implement `cycle` as mentioned above.

**Comment by moba1** [comment]
I think of implementing `Enumerable` module to `List` monad like you say.

**Pull request closed without merging**
